name: Deploy - Stockify

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do c√≥digo
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build da aplica√ß√£o
        run: mvn clean package -DskipTests=true

      - name: Copiar .jar para EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "target/stockify-0.0.1-SNAPSHOT.jar"
          target: "/home/ec2-user"

      - name: Reiniciar aplica√ß√£o via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "‚õî Parando aplica√ß√£o anterior (se estiver rodando)..."
            pkill -f 'stockify-0.0.1-SNAPSHOT.jar' || echo "Nenhum processo antigo encontrado."
            sleep 2

            echo "üöÄ Iniciando aplica√ß√£o com setsid + path correto..."
            setsid java -Dspring.profiles.active=prod -jar /home/ec2-user/stockify-0.0.1-SNAPSHOT.jar > output.log 2>&1 &

            sleep 3
            PID=$(pgrep -f stockify)

            if [ -n "$PID" ]; then
              echo "‚úÖ Aplica√ß√£o iniciada com PID $PID"
            else
              echo "‚ùå Falha ao iniciar aplica√ß√£o. √öltimas linhas do log:"
              tail -n 20 output.log
              exit 1
            fi