name: Deploy - Stockify

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do cÃ³digo
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build da aplicaÃ§Ã£o
        run: mvn clean package -DskipTests=true

      - name: Copiar .jar para EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "target/stockify-0.0.1-SNAPSHOT.jar"
          target: "/home/ec2-user"

      - name: Reiniciar aplicaÃ§Ã£o via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "ðŸ”„ Parando aplicaÃ§Ã£o anterior..."
            pkill -f 'stockify-0.0.1-SNAPSHOT.jar' || echo "Nenhum processo anterior."

            echo "ðŸš€ Iniciando nova aplicaÃ§Ã£o..."
            setsid nohup java -Dspring.profiles.active=prod -jar /home/ec2-user/stockify-0.0.1-SNAPSHOT.jar > output.log 2>&1 < /dev/null &

            sleep 5
            PID=$(pgrep -f stockify)
            if [ -n "$PID" ]; then
              echo "âœ… AplicaÃ§Ã£o iniciada com PID $PID"
            else
              echo "âŒ Falha ao iniciar aplicaÃ§Ã£o"
              tail -n 30 output.log
              exit 1
            fi